# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network :private_network, ip: "192.168.53.105"
  config.vm.network :forwarded_port, guest: 80, host: 18080, protocol: 'tcp'
  config.vm.network :forwarded_port, guest: 3306, host: 13306, protocol: 'tcp'
  config.vm.network :forwarded_port, guest: 2375, host: 12375, protocol: 'tcp'

  config.vm.provision "shell", path: "src/box/provision.sh"
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
    v.memory = 1024 
    v.cpus = 1
  end
end
